[package]
name = "ubjson"
description = "UBJSON parser"
documentation = "https://docs.rs/ubjson"
homepage = "https://github.com/OtaK/ubjson"
include = [
    "**/*.rs",
    "Cargo.toml",
]
keywords = [
    "ubjson",
    "ubj",
    "nom",
    "serde"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/OtaK/ubjson"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
nom = "6.0"
num_enum = "0.5.1"

[features]
default = []
spec2 = []

[dev-dependencies]
criterion = "0.3"
